stages:
  - build

job:
  stage: build
  script:
  - echo "Debug build..."
  - C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe ManagedClient.sln /t:Rebuild /p:Configuration=Debug   /p:TargetFrameworkVersion=v4.0   /p:OutputPath=bin\Debug40    /consoleloggerparameters:ErrorsOnly /p:DefineConstants="FW461;FW46;FW452;FW451;FW45;FW40"
  - ''
  - echo "Release build..."
  - C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe ManagedClient.sln /t:Rebuild /p:Configuration=Release  /p:TargetFrameworkVersion=v4.0   /p:OutputPath=bin\Release40    /consoleloggerparameters:ErrorsOnly /p:DefineConstants="FW461;FW46;FW452;FW451;FW45;FW40"
  - ''
  - echo "Build success."
  tags: 
  except:
  - tags