version: 1.9.3.{build}
configuration: Debug
image: Visual Studio 2017

clone_folder: C:\projects\managedclient

clone_depth: 1

init:
  - git config --global core.autocrlf true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'

nuget:
  account_feed: false
  project_feed: false

install:
  - python -m pip install --upgrade pip
  - pip install --upgrade pygount
  - pygount -f summary -s cs Source\Classic\Libs\AM.Core\AM
  - pygount -f summary -s cs Source\Classic\Libs\AM.Drawing\AM
  - pygount -f summary -s cs Source\Classic\Libs\AM.Win32\AM
  - pygount -f summary -s cs Source\Classic\Libs\AM.Windows.Forms\AM
  - pygount -f summary -s cs Source\Classic\Libs\ManagedIrbis\Source
  - pygount -f summary -s cs Source\Classic\Libs\IrbisUI\Source
  - pygount -f summary -s cs Source\Classic\Libs\RestfulIrbis\Source

before_build:
- cmd: nuget restore Source\ManagedIrbis.sln
- cmd: choco install opencover.portable
- cmd: choco install codecov

build:
  project: Source\ManagedIrbis.sln
  publish_nuget: false
  parallel: true
  verbosity: minimal

after_build:
- cmd: runPftTests.cmd
- cmd: compile.cmd
- cmd: compilecore2.cmd
- cmd: compiledroid17.cmd
- cmd: compileuap17.cmd
- cmd: cd Nuget
- cmd: packit.cmd
- cmd: cd ..

test_script:
- cmd: runcodecov.cmd

artifacts:
  - path: Binaries
    name: ManagedIrbis
  - path: Nuget\*.nupkg
    name: Nuget

deploy:
- provider: NuGet
  api_key:
    secure: IZZIZyDbjfCXEftqtCgTr/96da50AnxLND8VzxN/rtE62bGXxsAz7N97G8nYAyQB
  skip_symbols: true
  artifact: Nuget
  on:
    branch: nuget
