version: 1.6.0.{build}
configuration: Debug
image: Previous Visual Studio 2013
environment:
  packageVersion: 1.6.0

assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'

nuget:
  account_feed: false
  project_feed: false

build:
  project: ManagedClient.sln
  publish_nuget: false
  parallel: true
  verbosity: minimal

after_build:
  cmd: compile.cmd

artifacts:
  - path: Binaries
    name: ManagedClient

deploy:
- provider: FTP
  host: 77.222.42.228
  protocol: ftp
  username: alexeymnet_ftp
  password:
    secure: sLbeQTSV54foCg741X7Quw==  artifact: ManagedClient