version: 1.8.2.{build}
configuration: Debug
image: Visual Studio 2015

clone_folder: C:\projects\managedclient

clone_depth: 1
# shallow_clone: true

init:
  - git config --global core.autocrlf true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'

nuget:
  account_feed: false
  project_feed: false

before_build:
- cmd: nuget restore Source\ManagedIrbis.sln
- cmd: choco install opencover.portable
- cmd: choco install codecov

build:
  project: Source\ManagedIrbis.sln
  publish_nuget: false
  parallel: true
  verbosity: minimal

after_build:
- cmd: runPftTests.cmd
- cmd: compile.cmd
- cmd: compilecore.cmd
- cmd: compilecore2.cmd
- cmd: compiledroid.cmd
- cmd: compileuap.cmd
- cmd: compilesl.cmd
- cmd: compilewin81.cmd
- cmd: compilepcl.cmd
- cmd: cd Nuget
- cmd: packit.cmd

#test_script:
#- cd "C:\projects\managedclient\Source\UnitTests\bin\Debug"
#- OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:""C:\projects\managedclient\Source\UnitTests\bin\Debug\UnitTests.dll" -output:coverage.xml
#- codecov -f coverage.xml

artifacts:
  - path: Binaries
    name: ManagedIrbis
  - path: Nuget\*.nupkg
    name: Nuget
#  - path: Source\Classic\Apps\CniInvent\bin\Debug
#    name: CniInvent

deploy:
#- provider: FTP
#  host: 77.222.42.228
#  protocol: ftp
#  username: alexeymnet_ftp
#  password:
#    secure: s53ypkChfg2aeqatuQPkWg==
#  artifact: ManagedIrbis,Nuget
- provider: NuGet
  api_key:
    secure: IZZIZyDbjfCXEftqtCgTr/96da50AnxLND8VzxN/rtE62bGXxsAz7N97G8nYAyQB
  skip_symbols: true
  artifact: Nuget
  on:
    branch: nuget
