version: 1.6.1.{build}
configuration: Debug
image: Visual Studio 2015
environment:
  packageVersion: 1.6.1

assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'

nuget:
  account_feed: false
  project_feed: false

before_build:
- cmd: nuget restore ManagedIrbis.sln

build:
  project: ManagedIrbis.sln
  publish_nuget: false
  parallel: true
  verbosity: minimal

after_build:
- cmd: compile.cmd
- cmd: cd Nuget
- cmd: packit.cmd

artifacts:
  - path: Binaries
    name: ManagedIrbis
  - path: Nuget\*.nupkg
    name: Nuget

deploy:
- provider: FTP
  host: 77.222.42.228
  protocol: ftp
  username: alexeymnet_ftp
  password:
    secure: sLbeQTSV54foCg741X7Quw==  artifact: ManagedIrbis,Nuget