version: 1.8.11.{build}
configuration: Debug
image: Visual Studio 2015

clone_folder: C:\projects\managedclient

clone_depth: 1

init:
  - git config --global core.autocrlf true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'

nuget:
  account_feed: false
  project_feed: false

before_build:
- cmd: nuget restore Source\ManagedIrbis.sln
- cmd: choco install opencover.portable
- cmd: choco install codecov

build:
  project: Source\ManagedIrbis.sln
  publish_nuget: false
  parallel: true
  verbosity: minimal

after_build:
- cmd: runPftTests.cmd
- cmd: compile.cmd
- cmd: compilecore2.cmd
- cmd: compiledroid.cmd
- cmd: compileuap.cmd
- cmd: cd Nuget
- cmd: packit.cmd
- cmd: cd ..

test_script:
- cmd: runcodecov.cmd

artifacts:
  - path: Binaries
    name: ManagedIrbis
  - path: Nuget\*.nupkg
    name: Nuget

deploy:
- provider: NuGet
  api_key:
    secure: IZZIZyDbjfCXEftqtCgTr/96da50AnxLND8VzxN/rtE62bGXxsAz7N97G8nYAyQB
  skip_symbols: true
  artifact: Nuget
  on:
    branch: nuget
