version: 1.6.7.{build}
configuration: Debug
image: Visual Studio 2015

# clone_depth: 3
# shallow_clone: true

branches:
  only:
    - master
    - nuget

init:
  - git config --global core.autocrlf true

environment:
  packageVersion: 1.6.7

assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'

nuget:
  account_feed: false
  project_feed: false

before_build:
- cmd: nuget restore Source\ManagedIrbis.sln

build:
  project: Source\ManagedIrbis.sln
  publish_nuget: false
  parallel: true
  verbosity: minimal

after_build:
- cmd: compile.cmd
- cmd: compilecore.cmd
- cmd: compiledroid.cmd
- cmd: compileuap.cmd
- cmd: compilesl.cmd
- cmd: compilewin81.cmd
- cmd: compilepcl.cmd
- cmd: cd Nuget
- cmd: packit.cmd

artifacts:
  - path: Binaries
    name: ManagedIrbis
  - path: Nuget\*.nupkg
    name: Nuget
  - path: Source\Classic\Libs\AM.Istu\bin\Debug
    name: AM.Istu
  - path: Source\Classic\Apps\Garfield\bin\Debug
    name: Garfield

deploy:
- provider: FTP
  host: 77.222.42.228
  protocol: ftp
  username: alexeymnet_ftp
  password:
    secure: HSLxGTbqSk/C1YrPNoBA6g==  artifact: ManagedIrbis,Nuget- provider: NuGet  api_key:    secure: IZZIZyDbjfCXEftqtCgTr/96da50AnxLND8VzxN/rtE62bGXxsAz7N97G8nYAyQB  skip_symbols: true  artifact: Nuget  on:    branch: nuget